### ISSUE TITLE
Feature Request - support for multiple token borders

### ISSUE THREAD

**Issue by apoapostolov** [MrPrimate/vtta-tokenizer#1]
Support for PC and NPC border folders instead of default PC and NPC border. The DM can set both to same folder if needing a mixed folder. From a dropdown menu in the Tokenizer interface, the DM can select a token (it would be nice if scrolling in the dropdown shows a preview aside) and it exchanges the layer with the token with the new selected border.

This doesn't need to remove the current default PC and NPC borders, they are automatically selected by default. But the dropdown menu allows to select any other border available for PCs or NPC (such as boss, miniboss, etc.). 

The dropdown can be actually a modal dialog with a button that triggers access to it from this empty space:

![image](https://user-images.githubusercontent.com/4083812/97483616-521b2e80-1960-11eb-937a-bd1497ad0914.png)

**Comment by MrPrimate** [comment]
In 3.2.1
