### ISSUE TITLE
Portrait/Token does not save on a duplicate actor

### ISSUE THREAD

**Issue by 54m53p10L** [MrPrimate/vtta-tokenizer#11]
I'm using this on Pathfinder 2e. I duplicate an actor, change it's name, then try to change it's portrait and token. It does not save.

**Comment by 54m53p10L** [comment]
It seems it has to do with importing NPCs from the compendium and trying to change it's portrait from the default "mystery man". When trying to change the portrait, two errors pop up.

**Comment by MrPrimate** [comment]
Can you see if this still happens on the new 2.2.6 version?

**Comment by 54m53p10L** [comment]
It seems to be working correctly so far. Thank you!
