### ISSUE TITLE
Changes to CSS class names to allow Tokenizer and VTTA-Token to live together

### ISSUE THREAD

**Issue by apoapostolov** [MrPrimate/vtta-tokenizer#18]
The new VTTA Tokens mod uses a heavy grey/green theme that uses the same old CSS class and styles names as Tokenizer. This reskins Tokenizer in CSS style that doesn't fit the old design.

The best solution is to make all Tokenizer CSS entities to use new names that won't conflict.

**Comment by MrPrimate** [comment]
Resolved in 2.2.8
