### ISSUE TITLE
Failed to Load Token/Original Image error

### ISSUE THREAD

**Issue by twykomantis** [MrPrimate/vtta-tokenizer#19]
Looks like this was posted elsewhere: https://github.com/VTTAssets/vtta-tokenizer/issues/29

I've tried uninstalling the module, disabling all of the other modules, and have confirmed the folders in settings. Everything appears to be configured correctly, but I'm still getting the error and even though I can run through the interface to manually select an image, I'm unable to save the token or the image. 

![image](https://user-images.githubusercontent.com/74748853/113663279-9a9ced80-965e-11eb-8b5e-4c9f08532eb8.png)

**Comment by MrPrimate** [comment]
Please see v 3.0.0
