### ISSUE TITLE
Tokenizer Menu Not Functioning on PF2e World

### ISSUE THREAD

**Issue by korruption94** [MrPrimate/vtta-tokenizer#2]
When attempting to use the Tokenizer module to upload token art, everything works as expected until I hit the Save and Ok buttons that close the menu out. Upon doing this, I get the following error in the console and it does not update the actor's image at all. This problem didn't start occurring until 0.7.5 Foundry version.
![image](https://user-images.githubusercontent.com/73931936/98084177-0de8cc00-1e41-11eb-82a0-c55d5ddb074d.png)

Edit: It looks like this issue is fixed by choosing a directory for the token images to go to, as the module no longer default to uploading directly to the Data folder of Foundry.

**Comment by MrPrimate** [comment]
Should be fixed in 2.2.4
