### ISSUE TITLE
Webp format

### ISSUE THREAD

**Issue by g1eagle** [MrPrimate/vtta-tokenizer#23]
Can you make it possible for a saving in the webp format? they are smaller then the png's and would be better for the server. Also choosing a save location would be nice too.

**Comment by JamzTheMan** [comment]
@MrPrimate I have this working locally now if you want to assign it to me.  I'll submit a PR once I finish some more testing.

**Comment by MrPrimate** [comment]
@JamzTheMan Very cool, excited to see!

**Comment by JamzTheMan** [comment]
Pretty simple change. I also lumped in an extra option for portrait size, but if you don't like it I can remove it.

**Comment by MrPrimate** [comment]
Thanks for the great PR @JamzTheMan !
