### ISSUE TITLE
Irritating Popup

### ISSUE THREAD

**Issue by Bolt7** [MrPrimate/vtta-tokenizer#24]
Whenever opening their character sheet my players see this pop up:
"Tokenizer requires the permission to Upload Files. Please inform your Gamemaster."
I understand the purpose of the message, but would it be possible to say it when they try to change image instead of when opening the sheet? It's a bit annoying for it to pop up every time.

**Comment by MrPrimate** [comment]
This _is_ annoying, will only display a warning when you open Tokenizer as of 3.0.2
