### ISSUE TITLE
Changelog/Release Summary

### ISSUE THREAD

**Issue by DariusWolfe** [MrPrimate/vtta-tokenizer#25]
Hello,

This may be just a 'me' problem, but I like to read the Changelog updates or the summary of the changes in the Releases, as it gives me an idea of what to expect when I update modules, even if it's just bugfixes or minor tweaks. However there is no summary in the Releases, and the changelog hasn't been updated for over a year.

I've been a big fan of the module, though it was kind of unintuitive at first, and would like to be able to follow along with its development process.

**Comment by MrPrimate** [comment]
I have updated the changelog with this release and will try and remember in the future :)
