### ISSUE TITLE
Wrong download link in module.json

### ISSUE THREAD

**Issue by lunactic** [MrPrimate/vtta-tokenizer#33]
Hey

I think the module.json for 3.1.3 has a mixup in the download link.
The url still points to the zip for version 3.1.2 instead of 3.1.3 leading to an infinite update loop.

Cheers and thanks for all the work!

**Comment by MrPrimate** [comment]
🤦🏻

**Comment by MrPrimate** [comment]
Pushing 3.1.4 now.
