### ISSUE TITLE
[Feature Request] Add option to not save as new file

### ISSUE THREAD

**Issue by marcstraube** [MrPrimate/vtta-tokenizer#35]
First off, this is a great tool to allow my players to create their own tokens!
I keep a big archive of already optimized token and avatar images. I'd like to have an option to just choose an already available image and don't re-save it via Tokenizer, so it won't allocate space for the same image multiple times.

**Comment by filhit** [comment]
@marcstraube, does shift-clicking the avatar do what you want?

**Comment by scooper4711** [comment]
@filhit thanks for posting this workaround. Not super obvious to the casual user. Now that I know it's there, I'll use it.

The behavior I was expecting was if you change the setting to have tokenizer in the titlebar that it *wouldn't* open tokenizer when clicking on the avatar.

**Comment by MrPrimate** [comment]
> @filhit thanks for posting this workaround. Not super obvious to the casual user. Now that I know it's there, I'll use it.
> 
> The behavior I was expecting was if you change the setting to have tokenizer in the titlebar that it *wouldn't* open tokenizer when clicking on the avatar.

Ah, now a global option to disable launch on avatar click I could do!

**Comment by filhit** [comment]
I found this workaround by looking in the code. I'm not sure if it's documented.

**Comment by MrPrimate** [comment]
v3.4.6 now includes a toggle in the options to turn off tokenizer loading when the avatar is clicked - if you use this, you probably want to enable the option above it to get a Tokenizer button on the title bar.

**Comment by scooper4711** [comment]
Thanks!
