### ISSUE TITLE
Not working for Chinese name

### ISSUE THREAD

**Issue by bnp800** [MrPrimate/vtta-tokenizer#36]
This is an old issue left open from the original mod.
[https://github.com/VTTAssets/vtta-tokenizer/issues/18](url)

Still have this issue now.

**Comment by MrPrimate** [comment]
Fixed in v3.1.6

**Comment by bnp800** [comment]
> Fixed in v3.1.6

The mod are always "generating" for Chinese character name.

![image](https://user-images.githubusercontent.com/69395973/121795094-fa57dc00-cc3f-11eb-9e54-fe7885a50121.png)

I can give you some Chinese strings for test.

源
天下
打字机
上善若水
床前明月光
人之初性本善
飞流直下三千尺
窈窕淑女君子好逑

**Comment by MrPrimate** [comment]
Ah! I have made some bad assumptions about https support and the feature I used for this.

**Comment by MrPrimate** [comment]
Can you try v3.1.7 and let me know if that fixes the issue for you?

**Comment by bnp800** [comment]
Yes it works, thank you for your work!
