### ISSUE TITLE
Tokenizer Window Gets Cut Off

### ISSUE THREAD

**Issue by funwithfondue** [MrPrimate/vtta-tokenizer#37]
When you you open the tokenizer window from a player actor window, the tokenizer window is cut off leaving part of the right side hidden (see image below).

Steps to reproduce:
1. Launch FoundryVTT
2. Open world
3. Go to Actors Directory
4. Open player actor
5. Click on player icon
6. Notice that the tokenizer window gets cut off on the right side

Tokenizer version: 3.2.1
Foundry version: 0.8.8
Operating system: Windows 10

![image](https://user-images.githubusercontent.com/86520580/123512760-8aa70f80-d689-11eb-9f95-ed0176692dd3.png)

**Comment by erithtotl** [comment]
See issue 38, I have a fix for both.

**Comment by MrPrimate** [comment]
This doesn't happen on my system - if you disable all your other modules does it still happen?

**Comment by howdoicomputer** [comment]
I've also come across this issue. Maybe a conflict with another module?

**Comment by MrPrimate** [comment]
I will push a release that makes the frames drop down fixed width, as I suspect this may be the issue here.

**Comment by MrPrimate** [comment]
Please try version 3.2.2

**Comment by howdoicomputer** [comment]
There might be something wrong with how it was uploaded?

![Screenshot 2021-06-26 at 13-27-05 Foundry Virtual Tabletop • A Standalone Virtual Tabletop Application](https://user-images.githubusercontent.com/6774447/123524935-4a905e80-d682-11eb-81c5-1a118d8acaf3.png)

It's updating to `3.2.1` from `3.2.1`.

**Comment by MrPrimate** [comment]
🤦🏻 v3.2.3 is now available.

**Comment by howdoicomputer** [comment]
Yeah that super fixes.

**Comment by funwithfondue** [comment]
Confirming that this issue is now fixed with v3.2.3! Thanks a lot for the quick fix!

**Comment by howdoicomputer** [comment]
This issue is now showing up again as of version `v3.2.5`

**Comment by howdoicomputer** [comment]
![image](https://user-images.githubusercontent.com/6774447/124043163-59974980-d9bf-11eb-9777-ff18c61d12c6.png)

**Comment by MrPrimate** [comment]
That looks like a problem with whatever fancy ui your using rather than core - does this happen with the standard ui?

**Comment by funwithfondue** [comment]
Not happening with the standard UI for me.
