### ISSUE TITLE
Weird filenames cause tokenizer to break when loaded

### ISSUE THREAD

**Issue by erithtotl** [MrPrimate/vtta-tokenizer#38]
Because of the new title functionality, tokenizer can break if you have filenames that contain unusual characters like two underscores in a row.

Replace line 199 of utils.js with:
        words[i] = (words[i][0]?words[i][0].toUpperCase():'') + words[i].substr(1);

**Comment by erithtotl** [comment]
I went one step further, this also fixes the issue of the window getting cut off (its stretched because very long filenames)


  static titleString (text) {
    const words = text.trim().split(" ");

    for (let i = 0; i < words.length; i++) {
      if (i == 0 || !SKIPPING_WORDS.includes(words[i])) {
        words[i] = (words[i][0]?words[i][0].toUpperCase():'') + words[i].substr(1);
      }
    }

    return  words.join(" ").substring(0,40);
  }

**Comment by MrPrimate** [comment]
Please explain _how_ it breaks, I cannot replicate this.

Neither does it get cut off.
