### ISSUE TITLE
Tokenizer won't open

### ISSUE THREAD

**Issue by Opzehn** [MrPrimate/vtta-tokenizer#39]
Clicking on the avatar doesn't open up the Tokenizer window. Nothing happens.
Tried with all modules disabled except for Tokenzier on the 5e system.
Tried with Tokenizer, Tidy5e and Monster blocks in the 5e system.
Tried with all modules disabled except for Tokenizer on the PF2E system.

Tried on both Electrum & Chrome. Gives [this](https://i.imgur.com/7lGQ0gj.png) error in the console on chrome:

Tokenizer version: 3.2.3
Foundry version: 0.8.8
Operating system: Windows 10

**Comment by MrPrimate** [comment]
Please can you try version 3.2.4

**Comment by Opzehn** [comment]
Now it properly opens. Thanks for the quick fix!
