### ISSUE TITLE
Enhancement: add picture from clipboard

### ISSUE THREAD

**Issue by SR5060** [MrPrimate/vtta-tokenizer#40]
Not sure if this is even possible but it would be really handy to add a photo from the windows clipboard to use with screen clippings, this would save a few steps in the process

**Comment by MrPrimate** [comment]
I spent sometime looking at this but I'm not sure it's possible with the way Foundry currently interacts with paste events.

**Comment by apoapostolov** [comment]
The mod Chat Images allows pasting images into the chat. AFAIK it uploads the image to Imgur or something. Maybe their solution could be used in Tokenizer as well?

**Comment by MrPrimate** [comment]
@apoapostolov ah cool, I'll check that out!

**Comment by apoapostolov** [comment]
I think the workflow is sound. I know myself I always upload to Imgur before adding to Tokenizer :P

**Comment by MrPrimate** [comment]
Great success, now in v3.4.0
