### ISSUE TITLE
SecurityError: Operation is Insecure

### ISSUE THREAD

**Issue by drakeheath** [MrPrimate/vtta-tokenizer#44]
Tokenizer wont work, every time I try to add a picture to it it gives me a security error and the token frames wont load saying "Failed to Load Frame." When disabled I can add tokens and portraits, and when Tokenizer is the only module it still gives the error, so I don't think it's anything else.

**Comment by drakeheath** [comment]
I should also mention I'm using Forge as a server host, if that makes any difference.

**Comment by MrPrimate** [comment]
Okay, I think I know what this is, thanks for the report

**Comment by MrPrimate** [comment]
v3.3.3 will resolve this.
