### ISSUE TITLE
Option to copy paste into Avatar, instead into Token

### ISSUE THREAD

**Issue by apoapostolov** [MrPrimate/vtta-tokenizer#45]
A typical use case for adding an avatar token at the same time is to copy the image to the avatar, one-button copy it into the token area, and then set a frame (default or pick from recently implemented dropdown). 

The problem with copy-paste to Token area are numerous:
* there's no button to migrate the same image to avatar
* went he user uses the unlock button and zooms/pans the image to get closer to the face or fill a square portrait border (Tidy5E for example) then pass it to Token area, this now is impossible as Token Area accepts copy paste separately and needs to be manually zoom/panned to match. 

A switch to choose the default area to accept copy paste, or a Setting to make it default behavior will be very welcome. No matter what the default is for all users, this would allow me to set avatar area to accept copy paste.

**Comment by MrPrimate** [comment]
Great feedback, may v3.4.1 provide much satisfaction.
