### ISSUE TITLE
Won't generate a filename

### ISSUE THREAD

**Issue by Opzehn** [MrPrimate/vtta-tokenizer#48]
When you open up tokenizer, in the bottom right it'll get stuck on Target filename: Generating.... ([picture](https://i.imgur.com/GqvkWOt.png))
and saving a token names it as tmp-x-xxxxxxxxxxxx where X is random numbers, and the file type in the folder is just "file".
The token won't be updated, not even a blank token will be selected, rather it'll use the old one.

The console shows this [error](https://i.imgur.com/ilg4ctt.png).

EDIT: This seems to only happen with with Monster Blocks module. If opening via TidySheet or the default sheet, it works normally.

**Comment by MrPrimate** [comment]
I have an open PR that is not merged https://github.com/zeel01/MonsterBlocks/pull/98
