### ISSUE TITLE
Gamemaster cannot open Tokenizer since update

### ISSUE THREAD

**Issue by DoughyInTheMiddle** [MrPrimate/vtta-tokenizer#50]
I ran ran our Wednesday session just fine, and ran the update yesterday on 9/3, but didn't do much else withing FVTT.

Today, I went to check the paths for a couple of tokens, and double clicking didn't open Tokenizer. Couldn't edit the portrait image either. Could only change the token via the token tab.

Wracked my brain trying to figure out if I set some toggle incorrectly, and ended up after an hour just disabling all add-ons, and turning them on one by one. Not seeing any improvement, I turned everything off. Only then could I change the profile image.

Turned ONLY Tokenizer on and now it's locked and still Tokenizer won't open.

Results from log when I double click on the image:
```
foundry.js:2012 Uncaught (in promise) TypeError: Cannot create property 'message' on string 'Directory modules/vtta-tokenizer/img/custom does not exist or is not accessible in this storage location' at foundry.js:2012
(anonymous) @ foundry.js:2012
Promise.catch (async)
render @ foundry.js:2011
launchTokenizer @ hooks.js:176
tokenizeSceneToken @ hooks.js:248
tokenizeDoc @ hooks.js:254
(anonymous) @ hooks.js:321
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
```
I manually had to create the "custom" folder within "modules/vtta-tokenizer/img/" and now it's fine.

**Comment by MrPrimate** [comment]
This looks like maybe one of the tokenizer directories has been set to `modules/vtta-tokenizer/img/custom` - you should try not to keep custom content in the `modules` directory as when Foundry updates a module it deletes and recreates that folder.
