### ISSUE TITLE
can't use animated token webp 

### ISSUE THREAD

**Issue by radkonf** [MrPrimate/vtta-tokenizer#51]
Didn't fin anything in the FAQ, 
so is it jut me ? 
If I open a animated webp it saves it as still webp.

**Comment by radkonf** [comment]
I could use an animated wepm via shift click, but when I hen again click on token. I get following error message.
![Unbenannt](https://user-images.githubusercontent.com/79762867/132255205-e9d947b9-774a-427c-949b-4cf2b764ff03.PNG)
(if inline dosn't work.Here: https://imgur.com/a/50dxi7O)

**Comment by MrPrimate** [comment]
Tokenizer doesn't currently support animated tokens I'm afraid.

**Comment by radkonf** [comment]
Thanks so I know it's not me :)
DO you plan it in the foreseeable future?

**Comment by MrPrimate** [comment]
I would like to but animated things in the browser is _somewhat_ complicated right now. If anyone else reads this in the future, would love pointers to libraries/guides etc.
