### ISSUE TITLE
[Feature Request] Use Token Image as Avatar

### ISSUE THREAD

**Issue by asherett** [MrPrimate/vtta-tokenizer#52]
We currently have the "Use Avatar Image" function button for Tokens. I would love to have "Use Token Image" for Avatars. So basically another small button on the Add Layer row under Avatar, that adds the current Token image as avatar.

I believe previous (old) versions of VTTA-Tokens actually had this functionality. I find myself needing it quite often!

**Comment by MrPrimate** [comment]
This is in the latest version v3.4.9
