### ISSUE TITLE
Paste function applies to canvas too

### ISSUE THREAD

**Issue by SR5060** [MrPrimate/vtta-tokenizer#54]
Not sure if you are able to control this but it appear that the paste function will apply to both tokenizer and the canvas on the background (e.g. if I copy a token and then open tokenizer and paste a new image, the canvas will paste the token in addition to the expected paste function)

**Comment by MrPrimate** [comment]
This doesn't happen for me - can you confirm the version of Tokenizer, Foundry, System and the browser you are using?

**Comment by SR5060** [comment]
Foundry 0.8.9
Dnd 5e 1.4.3 (but this was occurring in the prior version too)
tokenizer 3.4.9 (but this was occurring in the prior version too)
Chrome

it's pretty replicable on my end, make sure I have copied a token. open up tokenizer in a actor sheet (any sheet). copy an image for the token or avatar and paste. The image will paste correctly but then you also receive a prompt behind the sheet indicating that the token was pasted as well

**Comment by MrPrimate** [comment]
Ah! The bit I had missed on the first read was the copying the token first - not sure if there is anything I can do to prevent its but will have a look.

**Comment by SR5060** [comment]
Yea may be unpreventable. A browser refresh clears out the first copy data so that's always a workaround (or I simply just make sure to look through the canvas and clean up any accidental copies) so it's not that big of a deal. The copy/paste feature had been amazing by the way

**Comment by MrPrimate** [comment]
Fixed in v3.4.11
