### ISSUE TITLE
3.4.8+ broke Moulinette File Picker image links for Tokenizer in The Forge

### ISSUE THREAD

**Issue by Biscolino** [MrPrimate/vtta-tokenizer#57]
After 3.4.8 I get a "GET 404" error. This is because tokenizer doesn't seem to take the full link from the Moulinette File Picker within the forge. The assets link is not correctly used by Tokenizer. It still works with 3.4.7. 

The errors can be seen below.
Edit: the first tokenizer log is when I use the default file browser, that works correctly.

![tokenizer_moulinette.png](https://user-images.githubusercontent.com/45340186/134881985-412228c9-5c9f-44f3-8889-2952ad502f11.png)

This does not occur with last version of Moulinette & Tokenizer 3.4.7, nor when shift + clicking to skip the tokenizer interface with tokenizer 3.4.11, nor when using the default file browser. 

It does happen with any tokenizer version after 3.4.7. 

Cheers!

**Comment by MrPrimate** [comment]
I can't replicate this locally, so suspect this is an interaction with Forge - I'll try and give this a test - if you're willing to reach out to me on Discord to get a bit more info about what you have blanked out in the images that would be super useful.

**Comment by MrPrimate** [comment]
Hopefully fixed in v 3.4.12
