### ISSUE TITLE
[BUG] 3.4.12 - NPC picture picker does not work

### ISSUE THREAD

**Issue by Dprasni** [MrPrimate/vtta-tokenizer#59]
NPC picture picker does not work, at least the UI does not pop up, only the normal image picker does.

On PC's it works fine.

I'm using SWN:R system (if it helps)

**Comment by MrPrimate** [comment]
Tokenizer looks for a class on the image in the source, it has a list of supported types here: https://github.com/MrPrimate/vtta-tokenizer/blob/master/src/hooks.js#L312

SWN:R will need to support one of these, or let me know what class I can look for that is unique to npc images. 

As a workaround in the settings you can select "Title link bar?" which will place a link to Tokenizer in the title bar of the character sheets.

**Comment by Dprasni** [comment]
Sadly i'm not a programmer so i cant tell you exactly what class it is. The SWN:R dev who works on the system should best be contacted about this issue.

As for the title token link, this seems to work, thx.
Thank you

**Comment by MrPrimate** [comment]
This was fixed upstrea,m
