### ISSUE TITLE
Feature request of change protrait file manually to prevent this bug

### ISSUE THREAD

**Issue by gcolgate** [MrPrimate/vtta-tokenizer#64]
Sometimes, like in this workflow: https://www.reddit.com/r/FoundryVTT/comments/s9fkw5/in_8_minutes_you_too_can_have_animated_portraits/

Note the answers to fix this issue are 'Turn off Tokenizer'

To fix this, provide an interface  to force tokenizer NOT to composite the portrait file but use it as-is. 
Currently there is no option to do so. 

Note that this functionality exists in the token: you can override the tokenizer's token by setting the image from the token settings in token prototype, which Tokenizer does not override, but no way to override the portrait to be a particular file and not composited.

**Comment by MrPrimate** [comment]
Just shift click on the portrait to open the default filepicker and by-pass tokenizer.
