### ISSUE TITLE
[Feature Request] When creating a token, don't also automatically create a new actor portrait

### ISSUE THREAD

**Issue by SwordofSpirit** [MrPrimate/vtta-tokenizer#66]
Current behavior: When you run Tokenizer on an actor it creates a duplicate of the portrait that you can edit, as well as letting you create and edit the token.

Problem: I'm usually not interesting in altering the portrait--I just want to create a nice token quickly. However, I get a new portrait bloating my data storage anyway, even when it's completely unnecessary. If I want to delete this new actor portrait and use the original, I have to manually repoint the portrait to the original (often a time consuming procedure) or I get no portrait.

Desired behavior: A setting would prevent Tokenizer from creating a new avatar portrait unless changes are made to the portrait, instead only creating a token and continuing to use the original image for the portrait.

**Comment by MrPrimate** [comment]
Resolved by @Kigoli
