### ISSUE TITLE
Depreciation warning on opening an actor sheet

### ISSUE THREAD

**Issue by marvin9257** [MrPrimate/vtta-tokenizer#67]
The change to FVTT v9 is causing this line (#307 of hooks.js) to show a warning (depreciation) each time an actor sheet is open:
https://github.com/MrPrimate/vtta-tokenizer/blob/e067b289b17317e40b38cf12d95414cbf585f5d9/src/hooks.js#L307

I think it should be 

`const doc = isNewerVersion(game.version, "0.8.2")  `
Thanks.

**Comment by MrPrimate** [comment]
Resovled.
