### ISSUE TITLE
Tokenizer Directories deleted after update

### ISSUE THREAD

**Issue by RoninTX** [MrPrimate/vtta-tokenizer#7]
After an update of both FoundryVTT and Tokenizer suddenly the directories under Tokenizer are gone.
And the module gives errors about it.

1) Already tried deleting and reinstall
2) it was the ONLY module active
![image](https://user-images.githubusercontent.com/42044120/101536857-dc60a480-399a-11eb-9f1a-50dfc4611c5a.png)

**Comment by MrPrimate** [comment]
I think this is because you are storing data under the modules directory - when a module is updated by foundry it replaces the who module folder.
