### ISSUE TITLE
Seems the mod no longer works?

### ISSUE THREAD

**Issue by PupperooX** [MrPrimate/vtta-tokenizer#8]
It doesn't have any functionality after the update

**Comment by MrPrimate** [comment]
This is probably because the directories for storing images need to be reset.

**Comment by wdawson** [comment]
I'm using a docker container for foundry and I had to make sure that I configured tokenizer with a directory with the correct permissions. There were no error messages even in the console. In case this helps anyone else, I'd follow @MrPrimate 's advice and double-check your directory.

![tokenizer](https://user-images.githubusercontent.com/132961/111260802-b15f9f80-85de-11eb-933d-e4d4ecc68000.jpg)
